[package]
name = "aloita"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }

[dev-dependencies]
libc = "0.2.158"
